ingress:
  host: chart-example.local
  ingressClassName: nginx

gitRepository: github.com/laszlocph/demo-app
gitSha: xyz

vars:
  MY_VAR: "value"

volumes:
  - name: testing
    path: /deleteme
    hostPath:
      path: /deleteme
  - name: empty
    path: /deleteme2
    emptyDir: true

deployment:
  annotations:
    keel.sh/policy: force
    keel.sh/pollSchedule: "@every 72h"
    keel.sh/trigger: poll
